AWSTemplateFormatVersion: "2010-09-09"
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://bdata-project.s3.eu-west-3.amazonaws.com/vpc.yaml"
  EKSClusterStack:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://bdata-project.s3.eu-west-3.amazonaws.com/eks-cluster.yaml"
      Parameters:
        PublicSubnet01Id: !GetAtt VPCStack.Outputs.PublicSubnet01Id
        PublicSubnet02Id: !GetAtt VPCStack.Outputs.PublicSubnet02Id
  EKSNodesStack:
    DependsOn: EKSClusterStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "https://bdata-project.s3.eu-west-3.amazonaws.com/managed-nodes.yaml"
      Parameters:
        PublicSubnet01Id: !GetAtt VPCStack.Outputs.PublicSubnet01Id
        PublicSubnet02Id: !GetAtt VPCStack.Outputs.PublicSubnet02Id
        ManagedNodesSshSecurityGroup: !GetAtt VPCStack.Outputs.SecurityGroupSsh
        ManagedNodesOpexSecurityGroup: !GetAtt VPCStack.Outputs.SecurityGroupOpex
        ClusterName: !GetAtt EKSClusterStack.Outputs.ClusterName
