kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-opex-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      component: kube-opex
  template:
    metadata:
      labels:
        component: kube-opex
    spec:
      serviceAccountName: opex-sa
      containers:
        - name: kube-opex
          image: rchakode/kube-opex-analytics
          ports:
            - containerPort: 5483
          volumeMounts:
          - name: opex-analytics-volume
            mountPath: /data
          env:
          - name: KOA_DB_LOCATION
            value: /data/db
          - name: KOA_K8S_API_ENDPOINT
            value: http://kubernetes.default.svc
      volumes:
      - name: opex-analytics-volume
        persistentVolumeClaim:
          claimName: opex-analytics-volume-claim
