apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: opex-role-binding
subjects:
- kind: ServiceAccount
  name: opex-sa # Name is case sensitive
  namespace: default
roleRef:
  kind: ClusterRole
  name: opex-role
  apiGroup: rbac.authorization.k8s.io
