apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: spark-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
